server:
  servlet:
    context-path: /order
  port: 8001
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.107.239.18:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: wdtx.2016
    druid:
      max-active: 2
      initial-size: 2
logging:
  level:
    com.weixiaoyi.distribute: info
